//! Build-time target selection, tuning profiles, and native-prime bitmap generation.

#![expect(
    clippy::exit,
    clippy::print_stderr,
    reason = "invalid build-time profile input must stop compilation with a diagnostic"
)]

use std::{
    env, fs,
    io::{Write, stdout},
    path::{Path, PathBuf},
    process::exit,
};

#[path = "build_support/prime_bitmap.rs"]
mod prime_bitmap;
#[path = "build_support/mod.rs"]
mod tuning;

use tuning::TuningProfile;

fn main() {
    emit_thread_local_configuration();

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let destination = Path::new(&out_dir).join("thresholds.rs");
    let manifest_dir = env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let root = Path::new(&manifest_dir);
    let tuned_path = root.join("src/int/tuned_thresholds.rs");
    let candidate_path = env::var_os("MP_TUNING_PROFILE").map(PathBuf::from);
    let content = candidate_path.as_deref().map_or_else(
        || resolve_installed_profile(&tuned_path),
        |path| resolve_candidate_profile(&root.join(path)),
    );

    if fs::read(&destination).ok().as_deref() != Some(content.as_bytes()) {
        fs::write(destination, content).expect("failed to write thresholds.rs");
    }
    let pointer_width = env::var("CARGO_CFG_TARGET_POINTER_WIDTH").unwrap_or_default();
    prime_bitmap::write_bitmap(
        &Path::new(&out_dir).join("prime_bitmap.bin"),
        &pointer_width,
    );

    drop(writeln!(stdout(), "cargo:rerun-if-changed=build.rs"));
    drop(writeln!(stdout(), "cargo:rerun-if-changed=build_support"));
    if tuned_path.exists() {
        drop(writeln!(
            stdout(),
            "cargo:rerun-if-changed=src/int/tuned_thresholds.rs"
        ));
    } else {
        // Cargo reruns on every invocation when a watched path does not exist.
        // Watching the parent detects profile creation without that repeated rerun.
        drop(writeln!(stdout(), "cargo:rerun-if-changed=src/int"));
    }
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-env-changed=MP_TUNING_PROFILE"
    ));

    emit_flint_search_path();
}

fn emit_thread_local_configuration() {
    // Native TLS and single-thread backends support eager const initialization.
    drop(writeln!(
        stdout(),
        "cargo:rustc-check-cfg=cfg(mp_eager_thread_local)"
    ));
    let target_family = env::var("CARGO_CFG_TARGET_FAMILY").unwrap_or_default();
    let target_features = env::var("CARGO_CFG_TARGET_FEATURE").unwrap_or_default();
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let single_thread_backend = (target_family.split(',').any(|family| family == "wasm")
        && !target_features
            .split(',')
            .any(|feature| feature == "atomics"))
        || matches!(target_os.as_str(), "uefi" | "zkvm" | "trusty" | "vexos");
    if env::var_os("CARGO_CFG_TARGET_THREAD_LOCAL").is_some() || single_thread_backend {
        drop(writeln!(stdout(), "cargo:rustc-cfg=mp_eager_thread_local"));
    }
}

fn resolve_installed_profile(tuned_path: &Path) -> String {
    if tuned_path.exists() {
        drop(writeln!(
            stdout(),
            "cargo:warning=mp_anafis: Using tuned profile from src/int/tuned_thresholds.rs"
        ));
        read_complete_profile(tuned_path)
    } else {
        let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
        let pointer_width = env::var("CARGO_CFG_TARGET_POINTER_WIDTH").unwrap_or_default();
        let profile = TuningProfile::for_target(&target_arch, &pointer_width);
        profile
            .validate()
            .expect("built-in tuning profile must satisfy tuning contracts");
        profile.render("// Automatically generated by build.rs")
    }
}

fn resolve_candidate_profile(path: &Path) -> String {
    drop(writeln!(
        stdout(),
        "cargo:warning=mp_anafis: Using autotuner candidate profile {}",
        path.display()
    ));
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-changed={}",
        path.display()
    ));
    read_complete_profile(path)
}

fn read_complete_profile(path: &Path) -> String {
    let source = fs::read_to_string(path).expect("failed to read tuning profile");
    let profile = TuningProfile::from_source(&source).unwrap_or_else(|error| {
        eprintln!(
            "mp_anafis: tuning profile {} could not be parsed: {error}",
            path.display()
        );
        exit(1);
    });
    if let Err(error) = profile.validate() {
        eprintln!(
            "mp_anafis: tuning profile {} failed semantic validation: {error}",
            path.display()
        );
        exit(1);
    }
    profile.render("// Validated tuning profile generated by build.rs")
}

/// Configures library search and runtime linker paths for external FLINT benchmarks.
///
/// On the Linux x86-64 benchmark host, `MP_ANAFIS_FLINT_LIB_DIR` supplies the
/// native library directory. Runtime search paths apply only to benchmark binaries.
fn emit_flint_search_path() {
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-env-changed=MP_ANAFIS_FLINT_LIB_DIR"
    ));
    let supported_host = env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("linux")
        && env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("x86_64")
        && env::var("CARGO_CFG_TARGET_POINTER_WIDTH").as_deref() == Ok("64");
    if supported_host && let Some(configured) = env::var_os("MP_ANAFIS_FLINT_LIB_DIR") {
        let dir = configured.to_string_lossy();
        drop(writeln!(stdout(), "cargo:rustc-link-search=native={dir}"));
        drop(writeln!(
            stdout(),
            "cargo:rustc-link-arg-benches=-Wl,-rpath,{dir}"
        ));
    }
}
