//! Build-time target selection and tuning-profile resolution.

use std::{
    env,
    fs::{self, File},
    io::{Write, stdout},
    path::Path,
};

#[path = "build_support/tuning.rs"]
mod tuning;

use tuning::{missing_definition, profile_for_target};

fn main() {
    emit_thread_local_configuration();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let destination = Path::new(&out_dir).join("thresholds.rs");
    let tuned_path = Path::new("src/int/tuned_thresholds.rs");
    let candidate_path = env::var_os("MP_TUNING_PROFILE").map(std::path::PathBuf::from);
    let content = candidate_path.as_deref().map_or_else(
        || resolve_installed_profile(tuned_path),
        resolve_candidate_profile,
    );

    File::create(destination)
        .expect("failed to create thresholds.rs")
        .write_all(content.as_bytes())
        .expect("failed to write thresholds");

    drop(writeln!(stdout(), "cargo:rerun-if-changed=build.rs"));
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-changed=build_support/tuning.rs"
    ));
    if tuned_path.exists() {
        drop(writeln!(
            stdout(),
            "cargo:rerun-if-changed=src/int/tuned_thresholds.rs"
        ));
    } else {
        // Watching a missing file makes Cargo rerun this build script on every
        // invocation. The directory watch detects creation of the optional
        // profile; once it exists, the narrower file watch above takes over.
        drop(writeln!(stdout(), "cargo:rerun-if-changed=src/int"));
    }
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-env-changed=MP_TUNING_PROFILE"
    ));

    emit_flint_search_path();
}

/// Points the `compare` benchmarks at a FLINT other than the system one.
///
/// Distribution packages routinely ship FLINT built for baseline x86-64, which
/// compiles out `fft_small` — its small-prime FFT needs AVX2 — and leaves the
/// legacy Schoenhage-Strassen fallback as the only large-operand path. A
/// comparison against that build understates FLINT by a wide margin, so
/// `MP_ANAFIS_FLINT_LIB_DIR` allows pointing at a locally built one. An rpath is
/// emitted alongside the search path so the benchmark also *runs* against it.
fn emit_flint_search_path() {
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-env-changed=MP_ANAFIS_FLINT_LIB_DIR"
    ));
    if let Some(configured) = env::var_os("MP_ANAFIS_FLINT_LIB_DIR") {
        let dir = configured.to_string_lossy();
        drop(writeln!(stdout(), "cargo:rustc-link-search=native={dir}"));
        drop(writeln!(stdout(), "cargo:rustc-link-arg=-Wl,-rpath,{dir}"));
    }
}

fn resolve_installed_profile(tuned_path: &Path) -> String {
    if tuned_path.exists() {
        drop(writeln!(
            stdout(),
            "cargo:warning=mp_anafis: Using tuned profile from src/int/tuned_thresholds.rs"
        ));
        read_complete_profile(tuned_path)
    } else {
        let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
        let pointer_width = env::var("CARGO_CFG_TARGET_POINTER_WIDTH").unwrap_or_default();
        profile_for_target(&target_arch, &pointer_width)
            .render("// Automatically generated by build.rs")
    }
}

fn resolve_candidate_profile(path: &Path) -> String {
    drop(writeln!(
        stdout(),
        "cargo:warning=mp_anafis: Using autotuner candidate profile {}",
        path.display()
    ));
    drop(writeln!(
        stdout(),
        "cargo:rerun-if-changed={}",
        path.display()
    ));
    read_complete_profile(path)
}

fn emit_thread_local_configuration() {
    // `cfg(target_thread_local)` is still unstable for library crates. Export
    // the eager-storage capability under a checked project cfg. Rust's
    // single-thread backends store `thread_local!` values in an ordinary static
    // and therefore support the same const initialization.
    drop(writeln!(
        stdout(),
        "cargo:rustc-check-cfg=cfg(mp_eager_thread_local)"
    ));
    let target_family = env::var("CARGO_CFG_TARGET_FAMILY").unwrap_or_default();
    let target_features = env::var("CARGO_CFG_TARGET_FEATURE").unwrap_or_default();
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let single_thread_backend = (target_family.split(',').any(|family| family == "wasm")
        && !target_features
            .split(',')
            .any(|feature| feature == "atomics"))
        || matches!(target_os.as_str(), "uefi" | "zkvm" | "trusty" | "vexos");
    if env::var_os("CARGO_CFG_TARGET_THREAD_LOCAL").is_some() || single_thread_backend {
        drop(writeln!(stdout(), "cargo:rustc-cfg=mp_eager_thread_local"));
    }
}

fn read_complete_profile(path: &Path) -> String {
    let source = fs::read_to_string(path).expect("failed to read tuning profile");
    let missing = missing_definition(&source);
    assert!(
        missing.is_none(),
        "mp_anafis: tuning profile {} is missing {missing:?}",
        path.display()
    );
    source
}
