[package]
name = "arbi-anafis-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
hex = "0.4.3"
rug = { version = "1.30.0", default-features = false, features = ["integer"] }

[dependencies.arbi-anafis]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "math_ops"
path = "fuzz_targets/math_ops.rs"
test = false
doc = false

[[bin]]
name = "int_ops"
path = "fuzz_targets/int_ops.rs"
test = false
doc = false
