//! Atomic publication of validated complete profiles.

use core::sync::atomic::{AtomicUsize, Ordering};
use std::{
    env::consts::{ARCH, OS},
    fs::{File, create_dir_all, remove_file, rename},
    io::{Error, ErrorKind, Result as IoResult, Write},
    path::Path,
    process::id as process_id,
};

use mp_anafis::tune_api::Limb;

use super::{MeasurementContext, TuningProfile};

/// Profile output, validation rejection preservation, and build overrides.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ProfileWriter;

impl ProfileWriter {
    /// Write a measured complete profile as the local build override.
    ///
    /// # Errors
    /// Returns an error if validation or atomic profile publication fails.
    pub fn write_profile(profile: &TuningProfile, cpu: &str, date: &str) -> IoResult<()> {
        let source = Self::render_with_header(profile, cpu, date);
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/int/tuned_thresholds.rs");
        Self::write_source(&source, &path)?;
        println!("Wrote complete tuned profile to {}", path.display());
        Ok(())
    }

    /// Write a rejected profile to the machine report directory for inspection.
    ///
    /// # Errors
    /// Returns an error if the directory or rejected profile cannot be written.
    pub fn write_rejected_profile(
        profile: &TuningProfile,
        directory: &Path,
        cpu: &str,
        date: &str,
    ) -> IoResult<()> {
        let source = Self::render_with_header(profile, cpu, date);
        create_dir_all(directory)?;
        let path = directory.join(format!("rejected-{date}.rs"));
        Self::write_source(&source, &path)?;
        println!(
            "Validation failed; the rejected profile was preserved at {}",
            path.display()
        );
        Ok(())
    }

    /// Write the built-in default for an unmeasured target as the local override.
    ///
    /// # Errors
    /// Returns an error if validation or atomic profile publication fails.
    pub fn write_arch_profile(profile: &TuningProfile, target_arch: &str) -> IoResult<()> {
        let header = format!(
            "// Built-in default for {target_arch} from build_support/.\n\
             // Rendered without measurements by `mp-tune --profile-for {target_arch}`.\n\
             // Generated local build override; keep this file untracked.",
        );
        let source = profile.render(&header);
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/int/tuned_thresholds.rs");
        Self::write_source(&source, &path)?;
        println!(
            "Wrote the {target_arch} architecture profile to {}",
            path.display()
        );
        Ok(())
    }

    /// Install the selected target's built-in default without measurement.
    ///
    /// # Errors
    /// Returns an error if the built-in profile cannot be published.
    pub fn write_target_profile(target_arch: &str) -> IoResult<()> {
        let profile =
            TuningProfile::for_target(target_arch, Self::conventional_pointer_width(target_arch));
        println!(
            "Installing the built-in default for {target_arch} \
             (this command performs no measurements)"
        );
        Self::write_arch_profile(&profile, target_arch)
    }

    /// Render the profile source with the measurement details.
    #[must_use]
    pub fn render_with_header(profile: &TuningProfile, cpu: &str, date: &str) -> String {
        let context = MeasurementContext::current().key();
        let header = format!(
            "// Tuning session profile generated by mp-tune.\n\
             // System: arch={}, os={}, cpu={}, limb_bits={}\n\
             // Measurement context: {}\n\
             // Tuned on: {}\n\
             // Generated local build override; keep this file untracked.",
            ARCH,
            OS,
            cpu,
            Limb::BITS,
            context,
            date,
        );
        profile.render(&header)
    }

    /// Write validated source code atomically to the destination file.
    /// The parent directory must already exist. Concurrent writers own separate
    /// temporary files; readers observe one complete valid profile after rename.
    ///
    /// # Errors
    /// Returns an error for invalid source or any publication failure. Invalid
    /// source is rejected before opening the destination or a temporary file.
    pub fn write_source(source: &str, path: &Path) -> IoResult<()> {
        static NEXT_ID: AtomicUsize = AtomicUsize::new(0);

        TuningProfile::from_source(source)
            .map_err(|error| Error::new(ErrorKind::InvalidInput, error))?
            .validate()
            .map_err(|error| Error::new(ErrorKind::InvalidInput, error))?;
        let (temporary, mut file) = loop {
            // The ordinal only names files; exclusive creation establishes
            // ownership, so its atomic ordering requires no data synchronization.
            let mut id = NEXT_ID.load(Ordering::Relaxed);
            loop {
                let next = id
                    .checked_add(1)
                    .ok_or_else(|| Error::other("profile temporary-file ordinal exhausted"))?;
                match NEXT_ID.compare_exchange_weak(id, next, Ordering::Relaxed, Ordering::Relaxed)
                {
                    Ok(_) => break,
                    Err(current) => id = current,
                }
            }
            let temporary = path.with_extension(format!("{}-{id}.tmp", process_id()));
            match File::create_new(&temporary) {
                Ok(file) => break (temporary, file),
                Err(error) if error.kind() == ErrorKind::AlreadyExists => {}
                Err(error) => return Err(error),
            }
        };
        let result = (|| {
            file.write_all(source.as_bytes())?;
            file.sync_all()?;
            drop(file);
            rename(&temporary, path)
        })();
        if result.is_err() {
            drop(remove_file(&temporary));
        }
        result
    }

    /// Conventional width for an architecture-only profile request.
    ///
    /// Real builds use the target's actual pointer width. `--profile-for` receives
    /// only an architecture name, so ambiguous ILP32 ABIs use their conventional
    /// architecture width.
    fn conventional_pointer_width(target_arch: &str) -> &'static str {
        match target_arch {
            "avr" | "msp430" => "16",
            "x86" | "arm" | "armv7" | "thumbv7neon" | "thumbv7a" | "thumbv7m" | "mips"
            | "mipsel" | "sparc" | "powerpc" | "sh" | "or1k" | "nios2" | "hexagon" | "csky"
            | "wasm32" | "riscv32" | "loongarch32" | "xtensa" | "m68k" => "32",
            _ => "64",
        }
    }
}
