//! Immutable candidate executables and complete worker captures.

use core::sync::atomic::{AtomicUsize, Ordering};
use std::{
    collections::HashMap,
    env::{consts::EXE_SUFFIX, temp_dir, var_os},
    ffi::OsString,
    fs::{File, copy, create_dir_all, read, read_to_string, remove_file, write},
    io::{Error, ErrorKind, Result as IoResult, Write},
    path::{Path, PathBuf},
    process::{Command, id as process_id},
    time::{SystemTime, UNIX_EPOCH},
};

use crate::worker::CellSelection;

use super::{ScoreStore, TuningProfile};

/// Builds each profile once, then executes its frozen binary without Cargo.
#[derive(Debug)]
pub struct Executables {
    directory: PathBuf,
    profiles: HashMap<u64, PathBuf>,
    source: CandidateFile,
    next_capture: usize,
}

impl Executables {
    pub fn new(parent: &Path) -> IoResult<Self> {
        let source = CandidateFile::new()?;
        let name = source.path.file_stem().expect("candidate has a file name");
        let directory = parent.join("workers").join(name);
        create_dir_all(&directory)?;
        Ok(Self {
            directory,
            profiles: HashMap::new(),
            source,
            next_capture: 0,
        })
    }

    /// Compile both sides before starting any paired measurement.
    pub fn prepare(&mut self, profile: &TuningProfile, features: &str) -> Result<PathBuf, String> {
        profile.validate().map_err(str::to_owned)?;
        let source = profile.render("// Temporary profile generated by mp-tune");
        let key = ScoreStore::fnv1a(format!("{features}\n{source}").as_bytes());
        if let Some(path) = self.profiles.get(&key) {
            return Ok(path.clone());
        }
        Self::write_candidate_source(&self.source.path, &source)
            .map_err(|error| error.to_string())?;
        let cargo = var_os("CARGO").unwrap_or_else(|| OsString::from("cargo"));
        let output = Command::new(cargo)
            .current_dir(env!("CARGO_MANIFEST_DIR"))
            .args([
                "build",
                "--release",
                "--locked",
                "--no-default-features",
                "--bin",
                "mp-tune",
                "--features",
                features,
                "--message-format=json-render-diagnostics",
            ])
            .env("MP_TUNING_PROFILE", &self.source.path)
            .env("CARGO_TARGET_DIR", self.directory.join("build"))
            .output()
            .map_err(|error| format!("cannot build candidate: {error}"))?;
        write(
            self.directory.join(format!("{key:016x}.build.stdout")),
            &output.stdout,
        )
        .map_err(|error| error.to_string())?;
        write(
            self.directory.join(format!("{key:016x}.build.stderr")),
            &output.stderr,
        )
        .map_err(|error| error.to_string())?;
        if !output.status.success() {
            return Err(format!(
                "candidate build failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        let stdout = String::from_utf8(output.stdout).map_err(|error| error.to_string())?;
        let artifact = Self::cargo_executable(&stdout)
            .ok_or_else(|| "Cargo did not report exactly one executable artifact".to_owned())?;
        let frozen = self.directory.join(format!("{key:016x}{EXE_SUFFIX}"));
        let _bytes = copy(&artifact, &frozen).map_err(|error| error.to_string())?;
        let bytes = read(&frozen).map_err(|error| error.to_string())?;
        write(
            self.directory.join(format!("{key:016x}.identity")),
            format!(
                "profile={key:016x}\nexecutable_fnv1a={:016x}\nfeatures={features}\n",
                ScoreStore::fnv1a(&bytes)
            ),
        )
        .map_err(|error| error.to_string())?;
        write(self.directory.join(format!("{key:016x}.rs")), source)
            .map_err(|error| error.to_string())?;
        drop(self.profiles.insert(key, frozen.clone()));
        Ok(frozen)
    }

    /// Retain raw worker samples, stderr, executable identity, and invocation order.
    pub fn run(
        &mut self,
        executable: &Path,
        flag: &str,
        prefix: &str,
        selected_cells: &[usize],
    ) -> Result<Vec<u128>, String> {
        let capture = self.directory.join(format!("run-{:06}", self.next_capture));
        self.next_capture = self
            .next_capture
            .checked_add(1)
            .expect("worker capture index fits");
        let selection = CellSelection::encode(selected_cells);
        write(
            capture.with_extension("command"),
            format!(
                "{}\n{flag}\nMP_TUNING_CELLS={selection}\n",
                executable.display()
            ),
        )
        .map_err(|error| error.to_string())?;
        let output = Command::new(executable)
            .current_dir(env!("CARGO_MANIFEST_DIR"))
            .arg(flag)
            .env("MP_TUNING_CELLS", selection)
            .output()
            .map_err(|error| format!("cannot execute candidate: {error}"))?;
        write(capture.with_extension("stdout"), &output.stdout)
            .map_err(|error| error.to_string())?;
        write(capture.with_extension("stderr"), &output.stderr)
            .map_err(|error| error.to_string())?;
        if !output.status.success() {
            return Err(format!(
                "candidate worker failed: {}",
                String::from_utf8_lossy(&output.stderr)
            ));
        }
        let stdout = String::from_utf8(output.stdout).map_err(|error| error.to_string())?;
        Self::parse_measurements(&stdout, prefix)
            .ok_or_else(|| "malformed candidate measurements".to_owned())
    }

    /// Decode Cargo's executable field, without assuming a target directory or ABI.
    pub fn cargo_executable(messages: &str) -> Option<PathBuf> {
        let mut executable = None;
        for line in messages.lines() {
            let Some((_, encoded)) = line.split_once("\"executable\":") else {
                continue;
            };
            let value = encoded.trim_start();
            if value.starts_with("null") {
                continue;
            }
            let mut characters = value.strip_prefix('"')?.chars();
            let mut path = String::new();
            let mut terminated = false;
            while let Some(character) = characters.next() {
                match character {
                    '"' => {
                        terminated = true;
                        break;
                    }
                    '\\' => path.push(match characters.next()? {
                        '"' => '"',
                        '\\' => '\\',
                        '/' => '/',
                        'n' => '\n',
                        'r' => '\r',
                        't' => '\t',
                        'b' => '\u{08}',
                        'f' => '\u{0c}',
                        'u' => {
                            let digits: String = characters.by_ref().take(4).collect();
                            if digits.len() != 4 {
                                return None;
                            }
                            char::from_u32(u32::from_str_radix(&digits, 16).ok()?)?
                        }
                        _ => return None,
                    }),
                    control if control.is_control() => return None,
                    ordinary => path.push(ordinary),
                }
            }
            if !terminated || path.is_empty() || executable.is_some() {
                return None;
            }
            executable = Some(PathBuf::from(path));
        }
        executable
    }

    /// Preserve the build-script input timestamp when only the worker probe changes.
    pub fn write_candidate_source(path: &Path, source: &str) -> IoResult<()> {
        if read_to_string(path).ok().as_deref() != Some(source) {
            let mut file = File::create(path)?;
            file.write_all(source.as_bytes())?;
        }
        Ok(())
    }

    /// Accept exactly one score line containing positive cell durations.
    pub fn parse_measurements(stdout: &str, prefix: &str) -> Option<Vec<u128>> {
        let mut lines = stdout.lines().filter_map(|line| line.strip_prefix(prefix));
        let encoded = lines.next()?;
        if lines.next().is_some() {
            return None;
        }
        let measurements = encoded
            .split(',')
            .map(str::parse::<u128>)
            .collect::<Result<Vec<_>, _>>()
            .ok()?;
        (!measurements.is_empty() && measurements.iter().all(|&value| value > 0))
            .then_some(measurements)
    }
}

/// Exclusively created temporary profile source, removed when dropped.
#[derive(Debug)]
pub struct CandidateFile {
    /// Source file used by this harness's candidate builds.
    pub path: PathBuf,
}

impl CandidateFile {
    /// Reserve a unique profile path without truncating another session's file.
    pub fn new() -> IoResult<Self> {
        static NEXT_ID: AtomicUsize = AtomicUsize::new(0);
        loop {
            let id = NEXT_ID.fetch_add(1, Ordering::Relaxed);
            let stamp = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_err(Error::other)?
                .as_nanos();
            let path =
                temp_dir().join(format!("mp-anafis-tuning-{}-{stamp}-{id}.rs", process_id()));
            match File::create_new(&path) {
                Ok(_) => return Ok(Self { path }),
                Err(error) if error.kind() == ErrorKind::AlreadyExists => {}
                Err(error) => return Err(error),
            }
        }
    }
}

impl Drop for CandidateFile {
    fn drop(&mut self) {
        drop(remove_file(&self.path));
    }
}
