//! Property tests for the Toom-Cook 4 tier.

use alloc::{vec, vec::Vec};

use proptest::prelude::*;

use super::*;
use crate::int::logic::math::mul::{Multiplication, Schoolbook};

fn balanced_operands() -> impl Strategy<Value = (Vec<Limb>, Vec<Limb>)> {
    prop_oneof![
        (
            proptest::collection::vec(any::<Limb>(), 4),
            proptest::collection::vec(any::<Limb>(), 4),
        ),
        (
            proptest::collection::vec(any::<Limb>(), 17),
            proptest::collection::vec(any::<Limb>(), 17),
        ),
        (
            proptest::collection::vec(any::<Limb>(), 71),
            proptest::collection::vec(any::<Limb>(), 71),
        ),
        (
            proptest::collection::vec(any::<Limb>(), 129),
            proptest::collection::vec(any::<Limb>(), 129),
        ),
        (
            proptest::collection::vec(any::<Limb>(), 257),
            proptest::collection::vec(any::<Limb>(), 257),
        ),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(8))]

    #[test]
    fn prop_toom4_matches_basecase((a, b) in balanced_operands()) {
        let result_len = a.len().wrapping_add(b.len());
        let mut expected = vec![0; result_len];
        let mut actual = vec![Limb::MAX; result_len];
        Schoolbook::mul(&mut expected, &a, &b);

        let scratch_len = Multiplication::toom4_mul_scratch_len(a.len(), b.len());
        let mut scratch = vec![Limb::MAX; scratch_len];
        Toom4::mul(&mut actual, &a, &b, &mut scratch);
        prop_assert_eq!(actual, expected);
    }

    #[test]
    fn prop_toom4_square_matches_basecase(a in proptest::collection::vec(any::<Limb>(), 4..258)) {
        let result_len = a.len().wrapping_mul(2);
        let mut expected = vec![0; result_len];
        let mut actual = vec![Limb::MAX; result_len];
        Schoolbook::sqr(&mut expected, &a);

        let scratch_len = Multiplication::toom4_sqr_scratch_len(a.len());
        let mut scratch = vec![Limb::MAX; scratch_len];
        Toom4::sqr(&mut actual, &a, &mut scratch);
        prop_assert_eq!(actual, expected);
    }
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(2))]

    #[test]
    fn prop_toom4_recursive_matches_basecase(
        a in proptest::collection::vec(any::<Limb>(), 1024..2050),
        b in proptest::collection::vec(any::<Limb>(), 1024..2050),
    ) {
        let result_len = a.len().wrapping_add(b.len());
        let mut expected = vec![0; result_len];
        let mut actual = vec![Limb::MAX; result_len];
        Schoolbook::mul(&mut expected, &a, &b);

        let scratch_len = Multiplication::toom4_mul_scratch_len(a.len(), b.len());
        let mut scratch = vec![Limb::MAX; scratch_len];
        Toom4::mul(&mut actual, &a, &b, &mut scratch);
        prop_assert_eq!(actual, expected);
    }
}

// The 381-limb operand is base^3 of the CI `int_ops` crash artifact (op=0x0e):
// the square that exercised the Toom-4 interpolation guard-carry bug during a
// `pow(14)`. Generated by tools (see fuzz corpus seed); do not edit by hand.
#[cfg(target_pointer_width = "64")]
#[rustfmt::skip]
#[allow(
    clippy::unreadable_literal,
    reason = "tool-generated regression operand; separators would obscure the 381-limb structure"
)]
const REGRESSION_OPERAND: [Limb; 381] = [
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 1099511627776000000,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 983040000, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    15406814325234466816, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 32985348833279999, 714240000, 0, 0, 0,
    32985348833280000, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 18446744069213257728, 18446744073709551615,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 7853151850246963199,
    0, 0, 0, 0, 19660800, 0,
    0, 0, 0, 0, 0, 0,
    0, 7782220156096217088, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0,
    0, 0, 18331902283211603968, 18446744071222853631, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 18331902283211603967, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 329853488332799, 2852902820604672000, 6442450944,
    0, 0, 659706976665600, 14284800, 0, 0,
    0, 329853488332800, 0, 0, 0, 0,
    16789419410786877440, 18446744073709551614, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073659219967,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    18446744073709551615, 78531518502371327, 850231296, 18446744073709551615, 18446744073709551615, 18446744073709551615,
    78531518502469631, 0, 0, 0, 0, 98304,
    0, 0, 0, 216172782113783808, 4680843264, 0,
    0, 0, 216172782113783808, 0, 0, 0,
    0, 0, 0, 0, 18445899648779419648, 11143312852961591295,
    18446744073709551615, 18446744073709551615, 18446744073709551615, 18445055223849287679, 18446744073672982527, 18446744073709551615,
    18446744073709551615, 18446744073709551615, 18445899648779419647, 18446744073709551615, 18446744073709551615, 1099511627775,
    28529028205975296, 205915392, 0, 0, 3298534883328, 28529028206046720,
    0, 0, 0, 3298534883328, 71424, 0,
    0, 0, 1099511627776,
];

/// Regression: Toom-4 reconstruction dropped an interpolation guard carry.
///
/// The operand is base^3 of the CI `int_ops` crash artifact: a 381-limb square
/// in the Toom-4 dispatch range whose evaluated coefficients produced a carry
/// into a full-limb guard. Before the fix, `reconstruct_around_quadratic`
/// added that carry to the guard's first limb without propagating it, so the
/// "interpolation guard dropped a carry" assertion fired; in release the carry
/// was silently lost and the product was wrong. The square now matches schoolbook.
#[cfg(target_pointer_width = "64")]
#[test]
fn regress_toom4_guard_carry() {
    // This test is gated to 64-bit `usize`, where `Limb == u64`, so the array
    // needs no conversion: `REGRESSION_OPERAND` is already `[Limb; 381]`.
    let a: Vec<Limb> = REGRESSION_OPERAND.to_vec();
    let result_len = a.len().wrapping_mul(2);
    let mut expected = vec![0; result_len];
    let mut actual = vec![Limb::MAX; result_len];
    Schoolbook::sqr(&mut expected, &a);

    let scratch_len = Multiplication::toom4_sqr_scratch_len(a.len());
    let mut scratch = vec![Limb::MAX; scratch_len];
    Toom4::sqr(&mut actual, &a, &mut scratch);
    assert_eq!(actual, expected);
}

/// Operands in the Toom-4 squaring dispatch range `[sqr_toom_cook_4,
/// sqr_toom_cook_6)` with limbs biased toward `Limb::MAX`, so interpolation
/// carries frequently collide with full-limb coefficient guards — the failure
/// class of the reconstruction carry bug.
fn toom4_square_operands() -> impl Strategy<Value = Vec<Limb>> {
    let len = 320..398_usize;
    let limb = prop_oneof![
        3 => Just(Limb::MAX),
        7 => any::<Limb>(),
    ];
    proptest::collection::vec(limb, len).prop_map(|mut v| {
        // Keep the operand normalized so the tier shape is stable. The length
        // range starts at 320, so the operand is never empty here.
        *v.last_mut().expect("length range 320..398 is never empty") |= 1;
        v
    })
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    #[test]
    fn prop_toom4_square_guard_range(a in toom4_square_operands()) {
        let result_len = a.len().wrapping_mul(2);
        let mut expected = vec![0; result_len];
        let mut actual = vec![Limb::MAX; result_len];
        Schoolbook::sqr(&mut expected, &a);

        let scratch_len = Multiplication::toom4_sqr_scratch_len(a.len());
        let mut scratch = vec![Limb::MAX; scratch_len];
        Toom4::sqr(&mut actual, &a, &mut scratch);
        prop_assert_eq!(actual, expected);
    }
}
