//! Validated tuned-profile output.

use std::{
    env::consts,
    fs::{self, File},
    io::Write,
    path::Path,
};

use arbi_anafis::tune_api::Limb;

use crate::tuning_profile::{TuningProfile, missing_definition};

/// Write a measured complete profile as the local build override.
pub fn write_profile(profile: &TuningProfile, cpu: &str, date: &str) {
    let source = render_with_header(profile, cpu, date);
    let path = Path::new("src/int/tuned_thresholds.rs");
    write_source(&source, path);
    println!("Wrote complete tuned profile to {}", path.display());
}

/// Write a rejected profile to the machine report directory for inspection.
///
/// The end-to-end validation rejected this profile; it is preserved so a
/// failing run can be inspected without installing it.
pub fn write_rejected_profile(profile: &TuningProfile, directory: &Path, cpu: &str, date: &str) {
    let source = render_with_header(profile, cpu, date);
    drop(fs::create_dir_all(directory));
    let path = directory.join(format!("rejected-{date}.rs"));
    write_source(&source, &path);
    println!(
        "Validation failed; the rejected profile was preserved at {}",
        path.display()
    );
}

/// Write the unmeasured architecture profile for a target that cannot run the
/// tuner, as the local build override.
pub fn write_arch_profile(profile: &TuningProfile, target_arch: &str) {
    let header = format!(
        "// Architecture profile for {target_arch} installed by `arbi-tune --profile-for {target_arch}`.\n\
         // These are reasoned defaults from build_support/tuning.rs, NOT measurements:\n\
         // the target cannot run the tuner. Supersede them with a measured profile\n\
         // whenever hardware becomes available.\n\
         // WARNING: machine- and target-specific; do not commit this generated override.",
    );
    let source = profile
        .render(&header)
        .replace(&(usize::MAX - 1).to_string(), "usize::MAX - 1");
    let path = Path::new("src/int/tuned_thresholds.rs");
    write_source(&source, path);
    println!(
        "Wrote the {target_arch} architecture profile to {}",
        path.display()
    );
}

/// Render the profile source with the machine provenance header.
#[must_use]
pub fn render_with_header(profile: &TuningProfile, cpu: &str, date: &str) -> String {
    let header = format!(
        "// Auto-tuned profile generated by `cargo run --bin arbi-tune --release --features _internal-tune`\n\
         // System: arch={}, os={}, cpu={}, limb_bits={}\n\
         // Tuned on: {}\n\
         // WARNING: machine-specific; do not commit this generated override.",
        consts::ARCH,
        consts::OS,
        cpu,
        Limb::BITS,
        date,
    );
    profile
        .render(&header)
        .replace(&(usize::MAX - 1).to_string(), "usize::MAX - 1")
}

fn write_source(source: &str, path: &Path) {
    let missing = missing_definition(source);
    assert!(
        missing.is_none(),
        "internal error: rendered profile is missing {missing:?}"
    );
    let mut file = File::create(path).expect("failed to create tuned profile");
    file.write_all(source.as_bytes())
        .expect("failed to write tuned profile");
}
