//! Errors for integer operations and string parsing.
//!
//! Operation errors describe arithmetic domains, precision limits, conversions,
//! and representation constraints. Parse errors distinguish invalid input,
//! invalid radix, and values exceeding bounded precision.

#[cfg(feature = "std")]
use core::error::Error;
use core::fmt::{Display, Formatter, Result as FmtResult};

/// A failure returned by an arbitrary-precision integer operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum MpError {
    /// Operation exceeds the maximum permitted precision bound.
    Overflow,
    /// Unsigned subtraction yields a negative result, or an operation underflows target precision.
    Underflow,
    /// Divisor is zero in a division or remainder operation.
    DivisionByZero,
    /// Radicand is negative in an even integer root operation.
    NegativeRoot,
    /// Modulus is even in an algorithm requiring an odd modulus.
    EvenModulusUnsupported,
    /// Modulus is zero in a modular arithmetic operation.
    ModulusZero,
    /// Modular inverse does not exist because the operand and modulus are not coprime.
    NoInverse,
    /// Modulus has no primitive root.
    NoPrimitiveRoot,
    /// Operands are not coprime.
    NotCoprime,
    /// Operation requires an explicit bit width, but unbounded precision is active.
    WidthRequired,
    /// The operation requires an explicit precision setting.
    PrecisionRequired,
    /// Requested bit shift exceeds the maximum representable bit width.
    ShiftTooLarge,
    /// Dynamic allocation is required, but memory allocation is unavailable in the current context.
    AllocationRequired,
    /// Radix is outside the supported range [2, 36].
    InvalidRadix,
    /// Input contains a digit invalid for the specified radix.
    InvalidDigit,
    /// Required integer factorization fails or is unavailable.
    FactorizationRequired,
    /// Limb buffer violates the canonical representation invariant.
    NonCanonical,
    /// Precision configurations do not match where required.
    PrecisionMismatch,
    /// Bounded target precision is insufficient to store the magnitude.
    PrecisionExceeded,
    /// Input buffer or digit sequence is empty when non-empty data is required.
    EmptyInput,
    /// Input is non-positive when a strictly positive value is required.
    NonPositiveInput,
    /// Input is negative when a non-negative value is required.
    NegativeInput,
    /// Modulus violates algorithm-specific domain preconditions.
    InvalidModulus,
    /// The group is not cyclic.
    NonCyclicGroup,
    /// Element does not belong to the subgroup generated by the base.
    NotInGeneratedSubgroup,
    /// Input value or formatting is invalid for construction or parsing.
    InvalidInput,
    /// Conversion loses precision or exceeds the target's representable range.
    IntegerConversionLoss,
    /// Slice operand is empty where a non-empty slice is required.
    EmptySlice,
}

/// An error parsing an [`MpInt`](crate::MpInt) from a string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseMpIntError {
    /// Specific cause of the integer parse failure.
    kind: ParseMpIntErrorKind,
}

/// Specific cause of an [`MpInt`](crate::MpInt) parsing failure.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum ParseMpIntErrorKind {
    /// Input string contains no digits.
    Empty,
    /// Input contains a character invalid for the specified radix.
    InvalidDigit,
    /// Specified radix is outside the supported range [2, 36].
    InvalidRadix,
    /// Parsed integer magnitude exceeds the target precision bound.
    TooLarge,
}

/// An error parsing an [`MpUint`](crate::MpUint) from a string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParseMpUintError {
    /// Specific cause of the unsigned integer parse failure.
    kind: ParseMpUintErrorKind,
}

/// Specific cause of an [`MpUint`](crate::MpUint) parsing failure.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum ParseMpUintErrorKind {
    /// Input string contains no digits.
    Empty,
    /// Specified radix is outside the supported range [2, 36].
    InvalidRadix,
    /// Input contains a character invalid for the specified radix.
    InvalidDigit,
    /// Input string contains a negative sign prefix for an unsigned integer.
    Negative,
    /// Parsed integer magnitude exceeds the target precision bound.
    TooLarge,
}

impl ParseMpIntError {
    /// Creates an internal parse error with the given cause.
    #[must_use]
    pub(crate) const fn new(kind: ParseMpIntErrorKind) -> Self {
        Self { kind }
    }

    /// Returns the specific cause of this error.
    #[must_use]
    #[inline]
    pub const fn kind(&self) -> &ParseMpIntErrorKind {
        &self.kind
    }
}

impl ParseMpUintError {
    /// Creates an internal parse error with the given cause.
    #[must_use]
    pub(crate) const fn new(kind: ParseMpUintErrorKind) -> Self {
        Self { kind }
    }

    /// Returns the specific cause of this error.
    #[must_use]
    #[inline]
    pub const fn kind(&self) -> &ParseMpUintErrorKind {
        &self.kind
    }
}

impl Display for MpError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match *self {
            Self::Overflow => write!(f, "overflow"),
            Self::Underflow => write!(f, "underflow"),
            Self::DivisionByZero => write!(f, "division by zero"),
            Self::NegativeRoot => write!(f, "negative root"),
            Self::EvenModulusUnsupported => write!(f, "even modulus unsupported"),
            Self::ModulusZero => write!(f, "modulus is zero"),
            Self::NoInverse => write!(f, "no modular inverse"),
            Self::NoPrimitiveRoot => write!(f, "no primitive root"),
            Self::NotCoprime => write!(f, "not coprime"),
            Self::WidthRequired => write!(f, "explicit width required for this operation"),
            Self::PrecisionRequired => write!(f, "explicit precision required"),
            Self::ShiftTooLarge => write!(f, "shift too large"),
            Self::AllocationRequired => write!(f, "allocation required in no_alloc mode"),
            Self::InvalidRadix => write!(f, "invalid radix"),
            Self::InvalidDigit => write!(f, "invalid digit"),
            Self::FactorizationRequired => write!(f, "factorization required"),
            Self::NonCanonical => write!(f, "non-canonical representation"),
            Self::PrecisionMismatch => write!(f, "precision mismatch"),
            Self::PrecisionExceeded => write!(f, "precision exceeded"),
            Self::EmptyInput => write!(f, "empty input"),
            Self::NonPositiveInput => write!(f, "non-positive input"),
            Self::NegativeInput => write!(f, "negative input"),
            Self::InvalidModulus => write!(f, "invalid modulus"),
            Self::NonCyclicGroup => write!(f, "non-cyclic group"),
            Self::NotInGeneratedSubgroup => write!(f, "not in generated subgroup"),
            Self::InvalidInput => write!(f, "invalid input"),
            Self::IntegerConversionLoss => write!(f, "integer conversion loss"),
            Self::EmptySlice => write!(f, "empty slice"),
        }
    }
}

#[cfg(feature = "std")]
impl Error for MpError {}

impl Display for ParseMpIntError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self.kind {
            ParseMpIntErrorKind::Empty => write!(f, "cannot parse integer from empty string"),
            ParseMpIntErrorKind::InvalidDigit => write!(f, "invalid digit found in string"),
            ParseMpIntErrorKind::InvalidRadix => write!(f, "invalid radix"),
            ParseMpIntErrorKind::TooLarge => write!(f, "value too large for parsing"),
        }
    }
}

#[cfg(feature = "std")]
impl Error for ParseMpIntError {}

impl Display for ParseMpUintError {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self.kind {
            ParseMpUintErrorKind::Empty => write!(f, "cannot parse integer from empty string"),
            ParseMpUintErrorKind::InvalidDigit => write!(f, "invalid digit found in string"),
            ParseMpUintErrorKind::InvalidRadix => write!(f, "invalid radix"),
            ParseMpUintErrorKind::Negative => {
                write!(f, "cannot parse unsigned integer from negative value")
            }
            ParseMpUintErrorKind::TooLarge => write!(f, "value too large for parsing"),
        }
    }
}

#[cfg(feature = "std")]
impl Error for ParseMpUintError {}
